authors = ["5ebec <hash.a5ebec@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"

[compat]
Franklin = "0.10.11"
julia = "1.5"
